### ISSUE TITLE
About the name...

### ISSUE THREAD

**Issue by GrahamBorland** [square/hephaestus#12]
Hephaestus.

It's hard to pronounce and spell. (I had to copy and paste it above, after I manually typed it wrong the first time.) Would you consider renaming this project to something simpler? Slightly tongue-in-cheek request, but in all sincerity, the name is a (mild) usability impediment. It makes it hard to discuss the library.

**Comment by carstenhag** [comment]
Also, the pronunciation between languages (for example English, Spanish and German) is wildly different. Intuitively as a German I'd say "he-fa-estus", without the "he" as a "hii".

**Comment by ed-george** [comment]
I am in total agreement here having a difficult to pronounce name ultimately limits discussion and collaboration.

As per the [discussion on Reddit](https://reddit.com/r/androiddev/comments/heop82/introducing_hephaestus), some developers have resorted to using a pronunciation guide in order to learn how to say the name. That particular guide rates the difficulty 4/5 for _native_ English speakers let alone non-native, making this library extremely difficult for the vast majority of the development community.

I think the name is 'cute' in its nod to mythology but I would pick being widely-pronounceable and recognizable over being cute any day. As I said in my Reddit post, the fact most of us are talking about the name and not the actual library shows that, in my opinion, it was a poor choice and I hope you reconsider it.

**Comment by vRallev** [comment]
I'm sorry to disappoint you, but we'll stick with the name. I guess a lot of people learnt today where the name comes from and a good history lesson is never wrong.

**Comment by chrisjenx** [comment]
This is very disappointing - how the heck do we (as developers / society) expect to solve discrimination when a simple issue of a name can't even be discussed and improved upon.

It's hard enough being dyslexic in day to day life without developers being completely tone deaf when someone has genuine concern. The dismissive and tone deaf attitude turned this from a genuine concern for many alike into unintentional discrimination.

**Comment by vRallev** [comment]
It's not my or Square's intention to discriminate anyone. The name originates from a historical figure and we didn't choose it to offend anyone. It involves more work than a global find-and-replace to rename the library. 

We'll discuss this internally again, but at the same time I won't promise anything. I hope you can also understand that we won't open a poll for how we name our open source projects.

**Comment by sanogueralorenzo** [comment]
Completely understand this issue as a Spanish & probably dyslexic person (not the first dyslexic issue I had).

I had to repeat the name 4 times till the American counterpart could understand what I was talking about.

While it is a cool name a good modern history lesson is that society also drops political / complex names for simplified ones

If you want to be understood without hassle just type/say:

square dagger plugin

**Comment by vRallev** [comment]
We discussed this internally and decided to rename the library. All arguments together convinced us. We appreciate the feedback. The new name will be "anvil".

**Comment by chrisjenx** [comment]
This is awesome to hear. This is why Square leads the world in OSS. 
If we ever get back to conferences again, drinks on me.

**Comment by vRallev** [comment]
The project was renamed. Note that the artifact ID also changed. Keep that in mind when upgrading.
```
plugins {
  id 'com.squareup.anvil' version "${latest_version}"
}
```
Thanks again for all the feedback.
